#!/usr/bin/env python3

#A side-scrolling time series resource monitor

from collections import deque
import argparse
import time

import GPUtil
import numpy as np
import psutil

psutil.virtual_memory()

class SystemMonitor:
  def __init__(self, width=60):
    self.cores     = psutil.cpu_count()
    self.gpus      = len(GPUtil.getGPUs())
    self.cpu_calcs = [deque(maxlen=width) for i in range(self.cores)]
    self.gpu_calcs = [deque(maxlen=width) for i in range(self.gpus)]
    self.gpu_mem   = [deque(maxlen=width) for i in range(self.gpus)]
    self.mem       = deque(maxlen=width)
    self.swap      = deque(maxlen=width)

    self.bars             = np.array([' ','▁','▂','▃','▄','▅','▆','▇','█'])
    self.calc_tick_values = np.linspace(0,100,len(self.bars))
    self.colors           = [31,32,33,34,35,36,37,91,92,93,94]

    self.last_proc = None
    self.last_clear = None

    print("\033[2J") #Clear the screen

  def update(self):
    self._update_cpu()
    self._update_gpu()
    self._update_ram()
    self._update_swap()

  def _render_calc(self, vals):
    return self.bars[np.digitize(vals, self.calc_tick_values)-1]

  def _update_cpu(self):
    self.current_cpus = np.array(psutil.cpu_percent(interval=0, percpu=True))
    for i, x in enumerate(self._render_calc(self.current_cpus)):
      self.cpu_calcs[i].append(x)

  def _update_gpu(self):
    ret      = GPUtil.getGPUs()
    self.current_gpu_calc = [100*x.load for x in ret]
    self.current_gpu_mem  = [100*x.memoryUtil for x in ret]
    for i, x in enumerate(self._render_calc(self.current_gpu_calc)):
      self.gpu_calcs[i].append(x)
    for i, x in enumerate(self._render_calc(self.current_gpu_mem)):
      self.gpu_mem[i].append(x)

  def _update_ram(self):
    self.current_mem = psutil.virtual_memory().percent
    self.mem.append(self._render_calc(self.current_mem))

  def _update_swap(self):
    self.current_swap = psutil.swap_memory().percent
    self.swap.append(self._render_calc(self.current_swap))

  def _print_top_procs(self, n=10, rate=1):
    if self.last_proc is not None and time.time()-self.last_proc<rate:
      return
    self.last_proc = time.time()

    self.proc_info = []
    for proc in psutil.process_iter():
        try:
            self.proc_info.append(proc.as_dict(attrs=['pid', 'name', 'cpu_percent']))
        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            pass

    self.proc_info.sort(key=lambda x: x['cpu_percent'], reverse=True)
    self.proc_info = self.proc_info[0:n] #Get head

    for x in self.proc_info:
      print("\033[2K{cpu_percent:4} {name:20} pid={pid}".format(**x))

  def print(self):
    self._clear_screen_at_interval()
    print("\033[1;1H") #Reset cursor position
    self._print_list(name="CPU",     lst=self.cpu_calcs, current=self.current_cpus)
    print("\033[2K")
    self._print_list(name="GPU",     lst=self.gpu_calcs, current=self.current_gpu_calc)
    self._print_list(name="GPU RAM", lst=self.gpu_mem,   current=self.current_gpu_mem)
    print("\033[2K")
    self._print_nonlist(name="RAM",  vals=self.mem,      current=self.current_mem)
    self._print_nonlist(name="Swap", vals=self.swap,     current=self.current_swap)
    print("\033[2K")
    self._print_top_procs()

  @staticmethod
  def _clear_screen():
    print("\033[1;1H")

  def _clear_screen_at_interval(self, rate=10):
    if self.last_clear is not None and time.time()-self.last_clear<rate:
      return
    self.last_clear = time.time()

    print("\033[2J") #Clear the screen

  def _print_list(self, name, lst, current=None):
    for i in range(len(lst)):
      print(f"\033[2K{name:7} {i:2}: \033[{self.colors[i%len(self.colors)]}m{self.bars[-1]}|", end='')
      print(''.join(lst[i]), end='')
      print(f"|{self.bars[-1]}\033[39m", end='')
      if current is None:
        print("")
      else:
        print(f" {current[i]:5.1f}%")

  def _print_nonlist(self, name, vals, current=None):
    print(f"\033[2K{name:5}     : {self.bars[-1]}|", end='')
    print(''.join(vals), end='')
    print(f"|{self.bars[-1]}\033[39m", end='')
    if current is None:
      print("")
    else:
      print(f" {current:5.1f}%")


def monitor(speed):
  sm = SystemMonitor()

  while True:
    time.sleep(speed)
    sm.update()
    sm.print()

if __name__=="__main__":
  parser = argparse.ArgumentParser(description="Richard's Top")
  parser.add_argument('--speed', '-s', default=0.1, type=float, help="How fast to scroll")

  args = parser.parse_args()
  monitor(speed=args.speed)